spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userCenter
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

server:
  port: 8080


